// Copyright (c) 2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<usdrt::population::IUtils_abi> : public usdrt::population::IUtils_abi
{
public:
    OMNI_PLUGIN_INTERFACE("usdrt::population::IUtils")


    void setXformValues(const omni::fabric::StageReaderWriterId stageId,
                        omni::fabric::PathC fcPath,
                        const usdrt::GfVec3d* translation,
                        const usdrt::GfQuatf* rotation,
                        const usdrt::GfVec3f* scale,
                        omni::fabric::TokenC visibility,
                        bool worldVisibility) noexcept;


    void addCube(const omni::fabric::StageReaderWriterId stageId,
                 omni::fabric::PathC fcPath,
                 const usdrt::GfVec3f* displayColor,
                 double size,
                 bool hasAnimatedXform,
                 const omni::fabric::TokenC* appliedSchemas,
                 size_t numappliedSchemas,
                 omni::fabric::PathC materialId,
                 int refinementLevel,
                 int protoIndex,
                 const omni::fabric::PathC* instancerPath,
                 size_t numPrimvars,
                 const usdrt::population::PrimvarAttributeDescription* primvars) noexcept;


    void addSphere(const omni::fabric::StageReaderWriterId stageId,
                   omni::fabric::PathC fcPath,
                   const usdrt::GfVec3f* displayColor,
                   double radius,
                   bool hasAnimatedXform,
                   const omni::fabric::TokenC* appliedSchemas,
                   size_t numappliedSchemas,
                   omni::fabric::PathC materialId,
                   int refinementLevel,
                   int protoIndex,
                   const omni::fabric::PathC* instancerPath,
                   size_t numPrimvars,
                   const usdrt::population::PrimvarAttributeDescription* primvars) noexcept;


    void addCone(const omni::fabric::StageReaderWriterId stageId,
                 omni::fabric::PathC fcPath,
                 const usdrt::GfVec3f* displayColor,
                 omni::fabric::TokenC fcAxis,
                 double height,
                 double radius,
                 bool hasAnimatedXform,
                 const omni::fabric::TokenC* appliedSchemas,
                 size_t numappliedSchemas,
                 omni::fabric::PathC materialId,
                 int refinementLevel,
                 int protoIndex,
                 const omni::fabric::PathC* instancerPath,
                 size_t numPrimvars,
                 const usdrt::population::PrimvarAttributeDescription* primvars) noexcept;


    void addCylinder(const omni::fabric::StageReaderWriterId stageId,
                     omni::fabric::PathC fcPath,
                     const usdrt::GfVec3f* displayColor,
                     omni::fabric::TokenC fcAxis,
                     double height,
                     double radius,
                     bool hasAnimatedXform,
                     const omni::fabric::TokenC* appliedSchemas,
                     size_t numappliedSchemas,
                     omni::fabric::PathC materialId,
                     int refinementLevel,
                     int protoIndex,
                     const omni::fabric::PathC* instancerPath,
                     size_t numPrimvars,
                     const usdrt::population::PrimvarAttributeDescription* primvars) noexcept;


    void addCapsule(const omni::fabric::StageReaderWriterId stageId,
                    omni::fabric::PathC fcPath,
                    const usdrt::GfVec3f* displayColor,
                    omni::fabric::TokenC fcAxis,
                    double height,
                    double radius,
                    bool hasAnimatedXform,
                    const omni::fabric::TokenC* appliedSchemas,
                    size_t numappliedSchemas,
                    omni::fabric::PathC materialId,
                    int refinementLevel,
                    int protoIndex,
                    const omni::fabric::PathC* instancerPath,
                    size_t numPrimvars,
                    const usdrt::population::PrimvarAttributeDescription* primvars) noexcept;


    void addGeomInstance(const omni::fabric::StageReaderWriterId stageId,
                         omni::fabric::PathC fcPath,
                         omni::fabric::TokenC primType,
                         omni::fabric::PathC protoPath,
                         int protoIndex,
                         bool hasAnimatedXform,
                         omni::fabric::PathC materialId,
                         bool isInstanceRoot) noexcept;


    void addInstancer(omni::fabric::StageReaderWriterId stageId,
                      omni::fabric::PathC fcPath,
                      bool hasAnimatedXform,
                      const omni::fabric::PathC* prototypes,
                      size_t numPrototypes,
                      const int* protoIndices,
                      size_t numProtoIndices,
                      const usdrt::GfVec3f* translations,
                      size_t numTranslations,
                      const usdrt::GfQuath* orientations,
                      size_t numOrientations,
                      const usdrt::GfVec3f* scales,
                      size_t numScales,
                      const omni::fabric::TokenC* appliedSchemas,
                      size_t numappliedSchemas,
                      omni::fabric::PathC instancerPath,
                      int protoIndex,
                      size_t numPrimvars,
                      const usdrt::population::PrimvarAttributeDescription* primvars) noexcept;


    void defineMeshWithSizes(omni::fabric::StageReaderWriterId stageId,
                             omni::fabric::PathC fcPath,
                             size_t points,
                             size_t faceVertexCounts,
                             size_t faceVertexIndices,
                             size_t subsets,
                             size_t subsetIndices,
                             bool isPrototype,
                             size_t numPrimvars,
                             const usdrt::population::PrimvarAttributeDescription* primvars,
                             size_t timeVaryingAttributes,
                             omni::fabric::TokenC subdivisionScheme,
                             omni::fabric::TokenC interpolateBoundary,
                             omni::fabric::TokenC faceVaryingLinearInterpolation,
                             omni::fabric::TokenC triangleSubdivisionRule,
                             size_t creaseIndices,
                             size_t creaseLengths,
                             size_t creaseSharpnesses,
                             size_t cornerIndices,
                             size_t cornerSharpnesses,
                             bool hasAnimatedXform,
                             const omni::fabric::TokenC* appliedSchemas,
                             size_t numappliedSchemas,
                             bool hasMaterial,
                             size_t holeIndices) noexcept;


    void populateXformAttributes(omni::fabric::StageReaderWriterId stageId,
                                 omni::fabric::PathC fcPath,
                                 const usdrt::GfVec3d* translation,
                                 const usdrt::GfQuatf* rotation,
                                 const usdrt::GfVec3f* scale,
                                 const usdrt::GfRange3d* worldExtent,
                                 const omni::fabric::TokenC* appliedSchemas,
                                 size_t numappliedSchemas) noexcept;


    void populateFromUsd(omni::fabric::StageReaderWriterId stageReaderWriterId,
                         omni::fabric::UsdStageId usdStageId,
                         omni::fabric::PathC primPathC,
                         usdrt::population::SceneStatistics* statistics,
                         double time) noexcept;


    void populateFromUsd(omni::fabric::StageReaderWriterId stageReaderWriterId,
                         omni::fabric::UsdStageId usdStageId,
                         const omni::fabric::PathC* primPathCs,
                         size_t numPrimPathCs,
                         usdrt::population::SceneStatistics* statistics,
                         double time,
                         bool diffMode) noexcept;


    void populateFromUsd(omni::fabric::StageReaderWriterId stageReaderWriterId,
                         omni::fabric::UsdStageId usdStageId,
                         bool enableNotice,
                         const omni::fabric::PathC* primPathCs,
                         size_t numPrimPathCs,
                         usdrt::population::SceneStatistics* statistics,
                         double time,
                         bool diffMode,
                         bool sparseOnly) noexcept;


    bool getEnableUsdNoticeHandling(omni::fabric::UsdStageId usdStageId) noexcept;


    void setEnableUsdNoticeHandling(omni::fabric::UsdStageId usdStageId,
                                    omni::fabric::FabricId fabricId,
                                    const bool value) noexcept;


    void applyPendingUsdUpdates(omni::fabric::UsdStageId usdStageId,
                                omni::fabric::StageReaderWriterId stageReaderWriterId,
                                double time) noexcept;


    void setExtent(omni::fabric::StageReaderWriterId stageReaderWriterId,
                   omni::fabric::PathC fcPath,
                   const usdrt::GfRange3d* localExtent,
                   const usdrt::GfRange3d* worldExtent) noexcept;


    void setMaterialPurpose(omni::fabric::FabricId fabricId, omni::fabric::TokenC materialPurposeC) noexcept;


    void setWorldXform(const omni::fabric::StageReaderWriterId stageId,
                       omni::fabric::PathC fcPath,
                       const usdrt::GfMatrix4d* xform,
                       omni::fabric::TokenC visibility,
                       bool worldVisibility) noexcept;


    bool isPopulated(omni::fabric::StageReaderWriterId stageReaderWriterId) noexcept;


    void detachMaterial(omni::fabric::StageReaderWriterId stageReaderWriterId, omni::fabric::PathC primPathC) noexcept;


    omni::fabric::PathC acquireOrCreateRtPopulator(const std::string& populatorIdentifier,
                                                   omni::fabric::StageReaderWriterId stageReaderWriterId,
                                                   omni::fabric::UsdStageId derivedDataStageId) noexcept;


    void releaseRtPopulator(omni::fabric::PathC populatorPathC) noexcept;


    omni::fabric::PathC getRenderSettingsPrimPath(omni::fabric::StageReaderWriterId stageReaderWriterId) noexcept;


    void getPopulationHash(omni::hash128_t* outHash) noexcept;


    void synchronizeToFabric(omni::fabric::UsdStageId usdStageId,
                             omni::fabric::StageReaderWriterId stageReaderWriterId,
                             usdrt::TimeChange timeChange,
                             usdrt::UsdTimeCode time) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline void omni::core::Generated<usdrt::population::IUtils_abi>::setXformValues(
    const omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    const usdrt::GfVec3d* translation,
    const usdrt::GfQuatf* rotation,
    const usdrt::GfVec3f* scale,
    omni::fabric::TokenC visibility,
    bool worldVisibility) noexcept
{
    setXformValues_abi(stageId, fcPath, translation, rotation, scale, visibility, worldVisibility);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::addCube(
    const omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    const usdrt::GfVec3f* displayColor,
    double size,
    bool hasAnimatedXform,
    const omni::fabric::TokenC* appliedSchemas,
    size_t numappliedSchemas,
    omni::fabric::PathC materialId,
    int refinementLevel,
    int protoIndex,
    const omni::fabric::PathC* instancerPath,
    size_t numPrimvars,
    const usdrt::population::PrimvarAttributeDescription* primvars) noexcept
{
    addCube_abi(stageId, fcPath, displayColor, size, hasAnimatedXform, appliedSchemas, numappliedSchemas, materialId,
                refinementLevel, protoIndex, instancerPath, numPrimvars, primvars);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::addSphere(
    const omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    const usdrt::GfVec3f* displayColor,
    double radius,
    bool hasAnimatedXform,
    const omni::fabric::TokenC* appliedSchemas,
    size_t numappliedSchemas,
    omni::fabric::PathC materialId,
    int refinementLevel,
    int protoIndex,
    const omni::fabric::PathC* instancerPath,
    size_t numPrimvars,
    const usdrt::population::PrimvarAttributeDescription* primvars) noexcept
{
    addSphere_abi(stageId, fcPath, displayColor, radius, hasAnimatedXform, appliedSchemas, numappliedSchemas,
                  materialId, refinementLevel, protoIndex, instancerPath, numPrimvars, primvars);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::addCone(
    const omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    const usdrt::GfVec3f* displayColor,
    omni::fabric::TokenC fcAxis,
    double height,
    double radius,
    bool hasAnimatedXform,
    const omni::fabric::TokenC* appliedSchemas,
    size_t numappliedSchemas,
    omni::fabric::PathC materialId,
    int refinementLevel,
    int protoIndex,
    const omni::fabric::PathC* instancerPath,
    size_t numPrimvars,
    const usdrt::population::PrimvarAttributeDescription* primvars) noexcept
{
    addCone_abi(stageId, fcPath, displayColor, fcAxis, height, radius, hasAnimatedXform, appliedSchemas,
                numappliedSchemas, materialId, refinementLevel, protoIndex, instancerPath, numPrimvars, primvars);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::addCylinder(
    const omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    const usdrt::GfVec3f* displayColor,
    omni::fabric::TokenC fcAxis,
    double height,
    double radius,
    bool hasAnimatedXform,
    const omni::fabric::TokenC* appliedSchemas,
    size_t numappliedSchemas,
    omni::fabric::PathC materialId,
    int refinementLevel,
    int protoIndex,
    const omni::fabric::PathC* instancerPath,
    size_t numPrimvars,
    const usdrt::population::PrimvarAttributeDescription* primvars) noexcept
{
    addCylinder_abi(stageId, fcPath, displayColor, fcAxis, height, radius, hasAnimatedXform, appliedSchemas,
                    numappliedSchemas, materialId, refinementLevel, protoIndex, instancerPath, numPrimvars, primvars);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::addCapsule(
    const omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    const usdrt::GfVec3f* displayColor,
    omni::fabric::TokenC fcAxis,
    double height,
    double radius,
    bool hasAnimatedXform,
    const omni::fabric::TokenC* appliedSchemas,
    size_t numappliedSchemas,
    omni::fabric::PathC materialId,
    int refinementLevel,
    int protoIndex,
    const omni::fabric::PathC* instancerPath,
    size_t numPrimvars,
    const usdrt::population::PrimvarAttributeDescription* primvars) noexcept
{
    addCapsule_abi(stageId, fcPath, displayColor, fcAxis, height, radius, hasAnimatedXform, appliedSchemas,
                   numappliedSchemas, materialId, refinementLevel, protoIndex, instancerPath, numPrimvars, primvars);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::addGeomInstance(
    const omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    omni::fabric::TokenC primType,
    omni::fabric::PathC protoPath,
    int protoIndex,
    bool hasAnimatedXform,
    omni::fabric::PathC materialId,
    bool isInstanceRoot) noexcept
{
    addGeomInstance_abi(stageId, fcPath, primType, protoPath, protoIndex, hasAnimatedXform, materialId, isInstanceRoot);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::addInstancer(
    omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    bool hasAnimatedXform,
    const omni::fabric::PathC* prototypes,
    size_t numPrototypes,
    const int* protoIndices,
    size_t numProtoIndices,
    const usdrt::GfVec3f* translations,
    size_t numTranslations,
    const usdrt::GfQuath* orientations,
    size_t numOrientations,
    const usdrt::GfVec3f* scales,
    size_t numScales,
    const omni::fabric::TokenC* appliedSchemas,
    size_t numappliedSchemas,
    omni::fabric::PathC instancerPath,
    int protoIndex,
    size_t numPrimvars,
    const usdrt::population::PrimvarAttributeDescription* primvars) noexcept
{
    addInstancer_abi(stageId, fcPath, hasAnimatedXform, prototypes, numPrototypes, protoIndices, numProtoIndices,
                     translations, numTranslations, orientations, numOrientations, scales, numScales, appliedSchemas,
                     numappliedSchemas, instancerPath, protoIndex, numPrimvars, primvars);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::defineMeshWithSizes(
    omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    size_t points,
    size_t faceVertexCounts,
    size_t faceVertexIndices,
    size_t subsets,
    size_t subsetIndices,
    bool isPrototype,
    size_t numPrimvars,
    const usdrt::population::PrimvarAttributeDescription* primvars,
    size_t timeVaryingAttributes,
    omni::fabric::TokenC subdivisionScheme,
    omni::fabric::TokenC interpolateBoundary,
    omni::fabric::TokenC faceVaryingLinearInterpolation,
    omni::fabric::TokenC triangleSubdivisionRule,
    size_t creaseIndices,
    size_t creaseLengths,
    size_t creaseSharpnesses,
    size_t cornerIndices,
    size_t cornerSharpnesses,
    bool hasAnimatedXform,
    const omni::fabric::TokenC* appliedSchemas,
    size_t numappliedSchemas,
    bool hasMaterial,
    size_t holeIndices) noexcept
{
    defineMeshWithSizes_abi(stageId, fcPath, points, faceVertexCounts, faceVertexIndices, subsets, subsetIndices,
                            isPrototype, numPrimvars, primvars, timeVaryingAttributes, subdivisionScheme,
                            interpolateBoundary, faceVaryingLinearInterpolation, triangleSubdivisionRule, creaseIndices,
                            creaseLengths, creaseSharpnesses, cornerIndices, cornerSharpnesses, hasAnimatedXform,
                            appliedSchemas, numappliedSchemas, hasMaterial, holeIndices);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::populateXformAttributes(
    omni::fabric::StageReaderWriterId stageId,
    omni::fabric::PathC fcPath,
    const usdrt::GfVec3d* translation,
    const usdrt::GfQuatf* rotation,
    const usdrt::GfVec3f* scale,
    const usdrt::GfRange3d* worldExtent,
    const omni::fabric::TokenC* appliedSchemas,
    size_t numappliedSchemas) noexcept
{
    populateXformAttributes_abi(
        stageId, fcPath, translation, rotation, scale, worldExtent, appliedSchemas, numappliedSchemas);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::populateFromUsd(
    omni::fabric::StageReaderWriterId stageReaderWriterId,
    omni::fabric::UsdStageId usdStageId,
    omni::fabric::PathC primPathC,
    usdrt::population::SceneStatistics* statistics,
    double time) noexcept
{
    populateFromUsd_abi(stageReaderWriterId, usdStageId, primPathC, statistics, time);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::populateFromUsd(
    omni::fabric::StageReaderWriterId stageReaderWriterId,
    omni::fabric::UsdStageId usdStageId,
    const omni::fabric::PathC* primPathCs,
    size_t numPrimPathCs,
    usdrt::population::SceneStatistics* statistics,
    double time,
    bool diffMode) noexcept
{
    populateFromUsd_abi(stageReaderWriterId, usdStageId, primPathCs, numPrimPathCs, statistics, time, diffMode);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::populateFromUsd(
    omni::fabric::StageReaderWriterId stageReaderWriterId,
    omni::fabric::UsdStageId usdStageId,
    bool enableNotice,
    const omni::fabric::PathC* primPathCs,
    size_t numPrimPathCs,
    usdrt::population::SceneStatistics* statistics,
    double time,
    bool diffMode,
    bool sparseOnly) noexcept
{
    populateFromUsd_abi(stageReaderWriterId, usdStageId, enableNotice, primPathCs, numPrimPathCs, statistics, time,
                        diffMode, sparseOnly);
}

inline bool omni::core::Generated<usdrt::population::IUtils_abi>::getEnableUsdNoticeHandling(
    omni::fabric::UsdStageId usdStageId) noexcept
{
    return getEnableUsdNoticeHandling_abi(usdStageId);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::setEnableUsdNoticeHandling(
    omni::fabric::UsdStageId usdStageId, omni::fabric::FabricId fabricId, const bool value) noexcept
{
    setEnableUsdNoticeHandling_abi(usdStageId, fabricId, value);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::applyPendingUsdUpdates(
    omni::fabric::UsdStageId usdStageId, omni::fabric::StageReaderWriterId stageReaderWriterId, double time) noexcept
{
    applyPendingUsdUpdates_abi(usdStageId, stageReaderWriterId, time);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::setExtent(
    omni::fabric::StageReaderWriterId stageReaderWriterId,
    omni::fabric::PathC fcPath,
    const usdrt::GfRange3d* localExtent,
    const usdrt::GfRange3d* worldExtent) noexcept
{
    setExtent_abi(stageReaderWriterId, fcPath, localExtent, worldExtent);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::setMaterialPurpose(
    omni::fabric::FabricId fabricId, omni::fabric::TokenC materialPurposeC) noexcept
{
    setMaterialPurpose_abi(fabricId, materialPurposeC);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::setWorldXform(const omni::fabric::StageReaderWriterId stageId,
                                                                                omni::fabric::PathC fcPath,
                                                                                const usdrt::GfMatrix4d* xform,
                                                                                omni::fabric::TokenC visibility,
                                                                                bool worldVisibility) noexcept
{
    setWorldXform_abi(stageId, fcPath, xform, visibility, worldVisibility);
}

inline bool omni::core::Generated<usdrt::population::IUtils_abi>::isPopulated(
    omni::fabric::StageReaderWriterId stageReaderWriterId) noexcept
{
    return isPopulated_abi(stageReaderWriterId);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::detachMaterial(
    omni::fabric::StageReaderWriterId stageReaderWriterId, omni::fabric::PathC primPathC) noexcept
{
    detachMaterial_abi(stageReaderWriterId, primPathC);
}

inline omni::fabric::PathC omni::core::Generated<usdrt::population::IUtils_abi>::acquireOrCreateRtPopulator(
    const std::string& populatorIdentifier,
    omni::fabric::StageReaderWriterId stageReaderWriterId,
    omni::fabric::UsdStageId derivedDataStageId) noexcept
{
    return acquireOrCreateRtPopulator_abi(populatorIdentifier, stageReaderWriterId, derivedDataStageId);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::releaseRtPopulator(omni::fabric::PathC populatorPathC) noexcept
{
    releaseRtPopulator_abi(populatorPathC);
}

inline omni::fabric::PathC omni::core::Generated<usdrt::population::IUtils_abi>::getRenderSettingsPrimPath(
    omni::fabric::StageReaderWriterId stageReaderWriterId) noexcept
{
    return getRenderSettingsPrimPath_abi(stageReaderWriterId);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::getPopulationHash(omni::hash128_t* outHash) noexcept
{
    getPopulationHash_abi(outHash);
}

inline void omni::core::Generated<usdrt::population::IUtils_abi>::synchronizeToFabric(
    omni::fabric::UsdStageId usdStageId,
    omni::fabric::StageReaderWriterId stageReaderWriterId,
    usdrt::TimeChange timeChange,
    usdrt::UsdTimeCode time) noexcept
{
    synchronizeToFabric_abi(usdStageId, stageReaderWriterId, timeChange, time);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
static_assert(std::is_standard_layout<usdrt::population::SceneStatistics>::value,
              "usdrt::population::SceneStatistics must be standard layout to be used in ONI ABI");
static_assert(std::is_standard_layout<usdrt::population::PrimvarAttributeDescription>::value,
              "usdrt::population::PrimvarAttributeDescription must be standard layout to be used in ONI ABI");
