#!/usr/bin/env bash

set -e

error_exit()
{
    echo "There was an error running python"
    exit 1
}

MY_DIR=$(realpath $(dirname ${BASH_SOURCE}))

# Setup python env from generated file (generated by tools/repoman/build.py)
if [ -f "${MY_DIR}/setup_python_env.sh" ]; then
    source ${MY_DIR}/setup_python_env.sh
fi

# The executable path will be where python is located. So we set Cabonite app path through env var:
export CARB_APP_PATH=${MY_DIR}

# By default use our python, but allow overriding it by checking if PYTHONEXE env var is defined:
if [ -z "${PYTHONEXE}" ]; then
    paths=(
        "${MY_DIR}/python/python"
        "${MY_DIR}/../../target-deps/python-3.11/python"
        "${MY_DIR}/../../target-deps/python-3.10/python"
        "${MY_DIR}/../../target-deps/python-3.9/python"
        "${MY_DIR}/../../target-deps/python-3.8/python"
    )
    for p in ${paths[@]}; do
        if [ -f "${p}" ]; then
            PYTHONEXE=$(realpath ${p})
            break;
        fi
    done
fi

$PYTHONEXE "$@" || error_exit
