
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.appwindow-09fb4a4770e03a8d.zip"

    [package.publish]
        kitVersion = "106.5.0+release.162063.eef547af.gl"
        date = 1734047710
        buildNumber = "106.5.0+release.162063.eef547af.gl"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp310"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kitHash]
            0 = "d02c707b"
