// Copyright (c) 2023-2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<usdrt::xformcache::ISharedXformCache_abi> : public usdrt::xformcache::ISharedXformCache_abi
{
public:
    OMNI_PLUGIN_INTERFACE("usdrt::xformcache::ISharedXformCache")


    bool hasCache(const omni::fabric::UsdStageId stageId) noexcept;


    bool clear() noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline bool omni::core::Generated<usdrt::xformcache::ISharedXformCache_abi>::hasCache(
    const omni::fabric::UsdStageId stageId) noexcept
{
    return hasCache_abi(stageId);
}

inline bool omni::core::Generated<usdrt::xformcache::ISharedXformCache_abi>::clear() noexcept
{
    return clear_abi();
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
