// Copyright (c) 2022-2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<usdrt::xformcache::IXformCache_abi> : public usdrt::xformcache::IXformCache_abi
{
public:
    OMNI_PLUGIN_INTERFACE("usdrt::xformcache::IXformCache")


    bool attachToStage(const omni::fabric::UsdStageId stageId) noexcept;


    omni::fabric::UsdStageId getStageId() noexcept;


    void syncXforms() noexcept;


    void syncTargetedXforms(const omni::fabric::PathC targetPath) noexcept;


    usdrt::GfMatrix4d getLatestWorldXform(const omni::fabric::PathC path) noexcept;


    usdrt::GfMatrix4d computeWorldXform(const omni::fabric::PathC path) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline bool omni::core::Generated<usdrt::xformcache::IXformCache_abi>::attachToStage(
    const omni::fabric::UsdStageId stageId) noexcept
{
    return attachToStage_abi(stageId);
}

inline omni::fabric::UsdStageId omni::core::Generated<usdrt::xformcache::IXformCache_abi>::getStageId() noexcept
{
    return getStageId_abi();
}

inline void omni::core::Generated<usdrt::xformcache::IXformCache_abi>::syncXforms() noexcept
{
    syncXforms_abi();
}

inline void omni::core::Generated<usdrt::xformcache::IXformCache_abi>::syncTargetedXforms(
    const omni::fabric::PathC targetPath) noexcept
{
    syncTargetedXforms_abi(targetPath);
}

inline usdrt::GfMatrix4d omni::core::Generated<usdrt::xformcache::IXformCache_abi>::getLatestWorldXform(
    const omni::fabric::PathC path) noexcept
{
    return getLatestWorldXform_abi(path);
}

inline usdrt::GfMatrix4d omni::core::Generated<usdrt::xformcache::IXformCache_abi>::computeWorldXform(
    const omni::fabric::PathC path) noexcept
{
    return computeWorldXform_abi(path);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
