// Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


/**
 * PrimView is an interface that provides a view to a set of prims for use with OmniGraph instancing.
 *
 * The prim view provides both a list of prims, and a layout of which prims can be treated as consecutive data in fabric
 *
 *
 */
template <>
class omni::core::Generated<omni::graph::core::IPrimView_abi> : public omni::graph::core::IPrimView_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::graph::core::IPrimView")

    /**
     * Returns the number of prims in this view.
     * @return the total number of prims in this view, regardless of the segments
     */
    size_t getPrimCount() noexcept;

    /**
     * Returns a readonly pointer to a list of prims, stored as Paths.
     *
     * The returned list may be used to access consective prims. If the given prim is part of a segment of size n
     * the returned pointer should be valid for all prims in that segment.
     * For example if there are two segments of prims listed:
     *      segment 0 starts at prim 0 and has 5 prims.
     *      segment 1 starts at prim 5 and contains 10 prims.
     * Calling getPrim path on segment index:
     *      0 returns a pointer to segments [0, 5)
     *      3 returns a pointer to segments [3, 5)
     *      4 returns a pointer to segment 4 only (i.e. [4,5))
     *      5 returns a pointer to segments [5, 15)
     *      10 returns a pointer to segments [10, 15)
     *
     * @param[in] index - the index of the prim to retrieve.
     * @returns A pointer to the prim path for prim at the given index. If the index is out of range
     *          returns nullptr.
     *
     */
    const omni::fabric::PathC* const getPrimPath(size_t index) noexcept;

    /**
     * Returns the number of segments in the view.
     * @return the number of segments in the view.
     */
    size_t getSegmentCount() noexcept;

    /**
     * Returns the number of prims in the segment at the given index
     *
     * @params[in] index The index of the segment to query
     * @returns The number of prims in the segment or 0 if the index is out of range.
     */
    size_t getSegmentSize(size_t index) noexcept;

    /**
     * Call this method to refresh the prim view. Use this method to test if the view has changed.
     *
     * @returns true, if the segments or prim paths have updated since the previous call.
     */
    bool refreshView() noexcept;

    /**
     * Called to bind the prim view to a fabric id.
     *
     * @params[in] The fabric Id to bind to.
     */
    void bind(omni::fabric::FabricId fabricId) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline size_t omni::core::Generated<omni::graph::core::IPrimView_abi>::getPrimCount() noexcept
{
    return getPrimCount_abi();
}

inline const omni::fabric::PathC* const omni::core::Generated<omni::graph::core::IPrimView_abi>::getPrimPath(size_t index) noexcept
{
    return getPrimPath_abi(index);
}

inline size_t omni::core::Generated<omni::graph::core::IPrimView_abi>::getSegmentCount() noexcept
{
    return getSegmentCount_abi();
}

inline size_t omni::core::Generated<omni::graph::core::IPrimView_abi>::getSegmentSize(size_t index) noexcept
{
    return getSegmentSize_abi(index);
}

inline bool omni::core::Generated<omni::graph::core::IPrimView_abi>::refreshView() noexcept
{
    return refreshView_abi();
}

inline void omni::core::Generated<omni::graph::core::IPrimView_abi>::bind(omni::fabric::FabricId fabricId) noexcept
{
    bind_abi(fabricId);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
