// Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


//! Interface extension for ISchedulingHints that adds a new "pure" hint
template <>
class omni::core::Generated<omni::graph::core::ISchedulingHints2_abi> : public omni::graph::core::ISchedulingHints2_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::graph::core::ISchedulingHints2")

    /**
     * Get the flag describing the node's purity state.
     *
     * @returns Value of the PurityStatus flag.
     */
    omni::graph::core::ePurityStatus getPurityStatus() noexcept;

    /**
     * Set the flag describing the node's purity status.
     *
     * @param[in] newPurityStatus New value of the PurityStatus flag.
     */
    void setPurityStatus(omni::graph::core::ePurityStatus newPurityStatus) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline omni::graph::core::ePurityStatus omni::core::Generated<omni::graph::core::ISchedulingHints2_abi>::getPurityStatus() noexcept
{
    return getPurityStatus_abi();
}

inline void omni::core::Generated<omni::graph::core::ISchedulingHints2_abi>::setPurityStatus(
    omni::graph::core::ePurityStatus newPurityStatus) noexcept
{
    setPurityStatus_abi(newPurityStatus);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
