// Copyright (c) 2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


/**
 * @brief Interface extension for IVariable that adds the ability to check if the variable is backed by Usd.
 */
template <>
class omni::core::Generated<omni::graph::core::IVariable3_abi> : public omni::graph::core::IVariable3_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::graph::core::IVariable3")

    /**
     * Returns whether the variable has an USD representation on the stage.
     *
     * @return True if the variable is backed by USD, false otherwise.
     */
    bool isBackedByUsd() noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline bool omni::core::Generated<omni::graph::core::IVariable3_abi>::isBackedByUsd() noexcept
{
    return isBackedByUsd_abi();
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
