// Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<omni::graph::core::unstable::IDirtyID3_abi> : public omni::graph::core::unstable::IDirtyID3_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::graph::core::unstable::IDirtyID3")

    //! @brief Opens a thread-local scope to ensure that a bundle is only made dirty once.
    //! @return An identifier of the scope.
    omni::graph::core::unstable::BundleWriteScopeId open() noexcept;

    //! @brief Closes a previously opened scope.
    //! Each call to open must be balanced with a call to close.
    //! Please use the BundleWriteBlock API helper to do this robustly.
    //! @param id The identifier that was returned by open.
    //! @return Success if closed successfully, Fail when the scope was not open
    omni::core::Result close(omni::graph::core::unstable::BundleWriteScopeId id) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline omni::graph::core::unstable::BundleWriteScopeId omni::core::Generated<
    omni::graph::core::unstable::IDirtyID3_abi>::open() noexcept
{
    return open_abi();
}

inline omni::core::Result omni::core::Generated<omni::graph::core::unstable::IDirtyID3_abi>::close(
    omni::graph::core::unstable::BundleWriteScopeId id) noexcept
{
    return close_abi(id);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
