// Copyright (c) 2023-2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<usdrt::IRtAssetPath_abi> : public usdrt::IRtAssetPath_abi
{
public:
    OMNI_PLUGIN_INTERFACE("usdrt::IRtAssetPath")


    omni::core::ObjectPtr<usdrt::IRtAssetPath> create(const char* assetPath) noexcept;


    omni::core::ObjectPtr<usdrt::IRtAssetPath> createWithResolved(const char* assetPath,
                                                                  const char* resolvedPath) noexcept;


    const char* getAssetPath() noexcept;


    const char* getResolvedPath() noexcept;


    omni::core::ObjectPtr<usdrt::IRtAssetPath> createFromFabric(const void* fabricAssetPath) noexcept;


    omni::fabric::TokenC getAssetPathC() noexcept;


    omni::fabric::TokenC getResolvedPathC() noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline omni::core::ObjectPtr<usdrt::IRtAssetPath> omni::core::Generated<usdrt::IRtAssetPath_abi>::create(
    const char* assetPath) noexcept
{
    return omni::core::steal(create_abi(assetPath));
}

inline omni::core::ObjectPtr<usdrt::IRtAssetPath> omni::core::Generated<usdrt::IRtAssetPath_abi>::createWithResolved(
    const char* assetPath, const char* resolvedPath) noexcept
{
    return omni::core::steal(createWithResolved_abi(assetPath, resolvedPath));
}

inline const char* omni::core::Generated<usdrt::IRtAssetPath_abi>::getAssetPath() noexcept
{
    return getAssetPath_abi();
}

inline const char* omni::core::Generated<usdrt::IRtAssetPath_abi>::getResolvedPath() noexcept
{
    return getResolvedPath_abi();
}

inline omni::core::ObjectPtr<usdrt::IRtAssetPath> omni::core::Generated<usdrt::IRtAssetPath_abi>::createFromFabric(
    const void* fabricAssetPath) noexcept
{
    return omni::core::steal(createFromFabric_abi(fabricAssetPath));
}

inline omni::fabric::TokenC omni::core::Generated<usdrt::IRtAssetPath_abi>::getAssetPathC() noexcept
{
    return getAssetPathC_abi();
}

inline omni::fabric::TokenC omni::core::Generated<usdrt::IRtAssetPath_abi>::getResolvedPathC() noexcept
{
    return getResolvedPathC_abi();
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
