// Copyright (c) 2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<usdrt::IRtCollection_abi> : public usdrt::IRtCollection_abi
{
public:
    OMNI_PLUGIN_INTERFACE("usdrt::IRtCollection")


    bool isCollectionAPIPath(omni::fabric::PathC primPath,
                             omni::fabric::TokenC property,
                             omni::fabric::TokenC* instanceName) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline bool omni::core::Generated<usdrt::IRtCollection_abi>::isCollectionAPIPath(omni::fabric::PathC primPath,
                                                                                 omni::fabric::TokenC property,
                                                                                 omni::fabric::TokenC* instanceName) noexcept
{
    return isCollectionAPIPath_abi(primPath, property, instanceName);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
