// Copyright (c) 2023-2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<usdrt::IRtPath_abi> : public usdrt::IRtPath_abi
{
public:
    OMNI_PLUGIN_INTERFACE("usdrt::IRtPath")


    omni::core::ObjectPtr<usdrt::IRtPath> create(omni::fabric::PathC primPart, omni::fabric::TokenC propPart) noexcept;


    void setPath(omni::fabric::PathC primPart, omni::fabric::TokenC propPart) noexcept;


    omni::fabric::PathC getPrimPart() noexcept;


    omni::fabric::TokenC getPropPart() noexcept;


    omni::fabric::TokenC getNameToken() noexcept;


    bool isAbsolutePath() noexcept;


    bool hasPrefix(omni::fabric::PathC primPart, omni::fabric::TokenC propPart) noexcept;


    omni::core::ObjectPtr<usdrt::IRtPath> ancestorsRangeIteratorIncrement() noexcept;


    omni::core::ObjectPtr<usdrt::IRtPath> replacePrefix(omni::fabric::PathC oldPrefixPrimPart,
                                                        omni::fabric::TokenC oldPrefixPropPart,
                                                        omni::fabric::PathC newPrefixPrimPart,
                                                        omni::fabric::TokenC newPrefixPropPart) noexcept;


    omni::core::ObjectPtr<usdrt::IRtPath> getCommonPrefix(omni::fabric::PathC primPart,
                                                          omni::fabric::TokenC propPart) noexcept;


    void removeCommonSuffix(omni::fabric::PathC primPart,
                            omni::fabric::TokenC propPart,
                            omni::core::ObjectParam<usdrt::IRtPath> result1,
                            omni::core::ObjectParam<usdrt::IRtPath> result2,
                            bool stopAtRootPrim) noexcept;


    bool isValidIdentifier(const char* name) noexcept;


    bool isValidNamespacedIdentifier(const char* name) noexcept;


    bool isValidPathString(const char* pathString, char* errMsg) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline omni::core::ObjectPtr<usdrt::IRtPath> omni::core::Generated<usdrt::IRtPath_abi>::create(
    omni::fabric::PathC primPart, omni::fabric::TokenC propPart) noexcept
{
    return omni::core::steal(create_abi(primPart, propPart));
}

inline void omni::core::Generated<usdrt::IRtPath_abi>::setPath(omni::fabric::PathC primPart,
                                                               omni::fabric::TokenC propPart) noexcept
{
    setPath_abi(primPart, propPart);
}

inline omni::fabric::PathC omni::core::Generated<usdrt::IRtPath_abi>::getPrimPart() noexcept
{
    return getPrimPart_abi();
}

inline omni::fabric::TokenC omni::core::Generated<usdrt::IRtPath_abi>::getPropPart() noexcept
{
    return getPropPart_abi();
}

inline omni::fabric::TokenC omni::core::Generated<usdrt::IRtPath_abi>::getNameToken() noexcept
{
    return getNameToken_abi();
}

inline bool omni::core::Generated<usdrt::IRtPath_abi>::isAbsolutePath() noexcept
{
    return isAbsolutePath_abi();
}

inline bool omni::core::Generated<usdrt::IRtPath_abi>::hasPrefix(omni::fabric::PathC primPart,
                                                                 omni::fabric::TokenC propPart) noexcept
{
    return hasPrefix_abi(primPart, propPart);
}

inline omni::core::ObjectPtr<usdrt::IRtPath> omni::core::Generated<usdrt::IRtPath_abi>::ancestorsRangeIteratorIncrement() noexcept
{
    return omni::core::steal(ancestorsRangeIteratorIncrement_abi());
}

inline omni::core::ObjectPtr<usdrt::IRtPath> omni::core::Generated<usdrt::IRtPath_abi>::replacePrefix(
    omni::fabric::PathC oldPrefixPrimPart,
    omni::fabric::TokenC oldPrefixPropPart,
    omni::fabric::PathC newPrefixPrimPart,
    omni::fabric::TokenC newPrefixPropPart) noexcept
{
    return omni::core::steal(
        replacePrefix_abi(oldPrefixPrimPart, oldPrefixPropPart, newPrefixPrimPart, newPrefixPropPart));
}

inline omni::core::ObjectPtr<usdrt::IRtPath> omni::core::Generated<usdrt::IRtPath_abi>::getCommonPrefix(
    omni::fabric::PathC primPart, omni::fabric::TokenC propPart) noexcept
{
    return omni::core::steal(getCommonPrefix_abi(primPart, propPart));
}

inline void omni::core::Generated<usdrt::IRtPath_abi>::removeCommonSuffix(omni::fabric::PathC primPart,
                                                                          omni::fabric::TokenC propPart,
                                                                          omni::core::ObjectParam<usdrt::IRtPath> result1,
                                                                          omni::core::ObjectParam<usdrt::IRtPath> result2,
                                                                          bool stopAtRootPrim) noexcept
{
    removeCommonSuffix_abi(primPart, propPart, result1.get(), result2.get(), stopAtRootPrim);
}

inline bool omni::core::Generated<usdrt::IRtPath_abi>::isValidIdentifier(const char* name) noexcept
{
    return isValidIdentifier_abi(name);
}

inline bool omni::core::Generated<usdrt::IRtPath_abi>::isValidNamespacedIdentifier(const char* name) noexcept
{
    return isValidNamespacedIdentifier_abi(name);
}

inline bool omni::core::Generated<usdrt::IRtPath_abi>::isValidPathString(const char* pathString, char* errMsg) noexcept
{
    return isValidPathString_abi(pathString, errMsg);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
