// Copyright (c) 2021-2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<usdrt::IRtPrim_abi> : public usdrt::IRtPrim_abi
{
public:
    OMNI_PLUGIN_INTERFACE("usdrt::IRtPrim")


    bool hasAttribute(omni::fabric::TokenC attrName) noexcept;


    omni::core::ObjectPtr<usdrt::IRtAttribute> getAttribute(omni::fabric::TokenC attrName) noexcept;


    omni::core::ObjectPtr<usdrt::IRtAttribute> createAttribute(omni::fabric::TokenC name,
                                                               omni::fabric::TypeC typeName,
                                                               bool custom,
                                                               usdrt::Variability varying) noexcept;


    bool hasRelationship(omni::fabric::TokenC relName) noexcept;


    omni::core::ObjectPtr<usdrt::IRtRelationship> getRelationship(omni::fabric::TokenC relName) noexcept;


    omni::core::ObjectPtr<usdrt::IRtRelationship> createRelationship(omni::fabric::TokenC relName, bool custom) noexcept;


    bool removeProperty(omni::fabric::TokenC propName) noexcept;


    omni::core::ObjectPtr<usdrt::IRtPrim> getChild(omni::fabric::TokenC name) noexcept;


    omni::core::ObjectPtr<usdrt::IRtPrim> getParent() noexcept;


    omni::core::ObjectPtr<usdrt::IRtPrim> getNextSibling() noexcept;


    omni::fabric::TokenC getTypeName() noexcept;


    bool setTypeName(omni::fabric::TokenC typeName) noexcept;


    bool hasAuthoredTypeName() noexcept;


    bool clearTypeName() noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline bool omni::core::Generated<usdrt::IRtPrim_abi>::hasAttribute(omni::fabric::TokenC attrName) noexcept
{
    return hasAttribute_abi(attrName);
}

inline omni::core::ObjectPtr<usdrt::IRtAttribute> omni::core::Generated<usdrt::IRtPrim_abi>::getAttribute(
    omni::fabric::TokenC attrName) noexcept
{
    return omni::core::steal(getAttribute_abi(attrName));
}

inline omni::core::ObjectPtr<usdrt::IRtAttribute> omni::core::Generated<usdrt::IRtPrim_abi>::createAttribute(
    omni::fabric::TokenC name, omni::fabric::TypeC typeName, bool custom, usdrt::Variability varying) noexcept
{
    return omni::core::steal(createAttribute_abi(name, typeName, custom, varying));
}

inline bool omni::core::Generated<usdrt::IRtPrim_abi>::hasRelationship(omni::fabric::TokenC relName) noexcept
{
    return hasRelationship_abi(relName);
}

inline omni::core::ObjectPtr<usdrt::IRtRelationship> omni::core::Generated<usdrt::IRtPrim_abi>::getRelationship(
    omni::fabric::TokenC relName) noexcept
{
    return omni::core::steal(getRelationship_abi(relName));
}

inline omni::core::ObjectPtr<usdrt::IRtRelationship> omni::core::Generated<usdrt::IRtPrim_abi>::createRelationship(
    omni::fabric::TokenC relName, bool custom) noexcept
{
    return omni::core::steal(createRelationship_abi(relName, custom));
}

inline bool omni::core::Generated<usdrt::IRtPrim_abi>::removeProperty(omni::fabric::TokenC propName) noexcept
{
    return removeProperty_abi(propName);
}

inline omni::core::ObjectPtr<usdrt::IRtPrim> omni::core::Generated<usdrt::IRtPrim_abi>::getChild(
    omni::fabric::TokenC name) noexcept
{
    return omni::core::steal(getChild_abi(name));
}

inline omni::core::ObjectPtr<usdrt::IRtPrim> omni::core::Generated<usdrt::IRtPrim_abi>::getParent() noexcept
{
    return omni::core::steal(getParent_abi());
}

inline omni::core::ObjectPtr<usdrt::IRtPrim> omni::core::Generated<usdrt::IRtPrim_abi>::getNextSibling() noexcept
{
    return omni::core::steal(getNextSibling_abi());
}

inline omni::fabric::TokenC omni::core::Generated<usdrt::IRtPrim_abi>::getTypeName() noexcept
{
    return getTypeName_abi();
}

inline bool omni::core::Generated<usdrt::IRtPrim_abi>::setTypeName(omni::fabric::TokenC typeName) noexcept
{
    return setTypeName_abi(typeName);
}

inline bool omni::core::Generated<usdrt::IRtPrim_abi>::hasAuthoredTypeName() noexcept
{
    return hasAuthoredTypeName_abi();
}

inline bool omni::core::Generated<usdrt::IRtPrim_abi>::clearTypeName() noexcept
{
    return clearTypeName_abi();
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
