// Copyright (c) 2022-2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<usdrt::IRtRelationship_abi> : public usdrt::IRtRelationship_abi
{
public:
    OMNI_PLUGIN_INTERFACE("usdrt::IRtRelationship")


    bool hasAuthoredTargets() noexcept;


    bool addTarget(omni::fabric::PathC path, usdrt::ListPosition position) noexcept;


    bool removeTarget(omni::fabric::PathC path) noexcept;


    bool setTargets(const omni::fabric::PathC* paths, uint32_t size) noexcept;


    bool clearTargets() noexcept;


    uint32_t numTargets() noexcept;


    bool getTargets(omni::fabric::PathC* paths, uint32_t size) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline bool omni::core::Generated<usdrt::IRtRelationship_abi>::hasAuthoredTargets() noexcept
{
    return hasAuthoredTargets_abi();
}

inline bool omni::core::Generated<usdrt::IRtRelationship_abi>::addTarget(omni::fabric::PathC path,
                                                                         usdrt::ListPosition position) noexcept
{
    return addTarget_abi(path, position);
}

inline bool omni::core::Generated<usdrt::IRtRelationship_abi>::removeTarget(omni::fabric::PathC path) noexcept
{
    return removeTarget_abi(path);
}

inline bool omni::core::Generated<usdrt::IRtRelationship_abi>::setTargets(const omni::fabric::PathC* paths,
                                                                          uint32_t size) noexcept
{
    return setTargets_abi(paths, size);
}

inline bool omni::core::Generated<usdrt::IRtRelationship_abi>::clearTargets() noexcept
{
    return clearTargets_abi();
}

inline uint32_t omni::core::Generated<usdrt::IRtRelationship_abi>::numTargets() noexcept
{
    return numTargets_abi();
}

inline bool omni::core::Generated<usdrt::IRtRelationship_abi>::getTargets(omni::fabric::PathC* paths, uint32_t size) noexcept
{
    return getTargets_abi(paths, size);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
