// Copyright (c) 2022-2023, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


//! Interface for accessing global execution graph settings.
//!
//! This interface is a singleton. The settings are applied to all graphs.
//!
//! Access the singleton with @ref omni::kit::exec::core::unstable::getExecutionGraphSettings().
template <>
class omni::core::Generated<omni::kit::exec::core::unstable::IExecutionGraphSettings_abi>
    : public omni::kit::exec::core::unstable::IExecutionGraphSettings_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::kit::exec::core::unstable::IExecutionGraphSettings")

    //! If @c true all tasks will skip the scheduler and be executed immediately.
    bool shouldForceSerial() noexcept;

    //! If @c true all tasks will be given to the scheduler and marked as being able to execute in parallel.
    bool shouldForceParallel() noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline bool omni::core::Generated<omni::kit::exec::core::unstable::IExecutionGraphSettings_abi>::shouldForceSerial() noexcept
{
    return shouldForceSerial_abi();
}

inline bool omni::core::Generated<omni::kit::exec::core::unstable::IExecutionGraphSettings_abi>::shouldForceParallel() noexcept
{
    return shouldForceParallel_abi();
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
