// Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


//! Returns a global scheduler state based on TBB.
//!
//! This object is a singleton.  Access it with @ref omni::kit::exec::core::unstable::getTbbSchedulerState().
//!
//! Use of this object should be transparent to the user as it is an implementation detail of
//! @ref omni::kit::exec::core::unstable::ParallelSpawner.
//!
//! Temporary interface.  Will be replaced with something more generic.
template <>
class omni::core::Generated<omni::kit::exec::core::unstable::ITbbSchedulerState_abi>
    : public omni::kit::exec::core::unstable::ITbbSchedulerState_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::kit::exec::core::unstable::ITbbSchedulerState")

    //! Returns the needed data to access the serial task queue.
    omni::kit::exec::core::unstable::TbbSchedulerState* getState() noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline omni::kit::exec::core::unstable::TbbSchedulerState* omni::core::Generated<
    omni::kit::exec::core::unstable::ITbbSchedulerState_abi>::getState() noexcept
{
    return getState_abi();
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
