// Copyright (c) 2023-2024, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi> : public usdrt::hierarchy::IFabricHierarchy_abi
{
public:
    OMNI_PLUGIN_INTERFACE("usdrt::hierarchy::IFabricHierarchy")


    omni::fabric::FabricId getFabricId() noexcept;


    void updateWorldXforms() noexcept;


    usdrt::GfMatrix4d getLocalXform(const omni::fabric::PathC path) noexcept;


    bool setLocalXform(const omni::fabric::PathC path, const usdrt::GfMatrix4d xform) noexcept;


    usdrt::GfMatrix4d getWorldXform(const omni::fabric::PathC path) noexcept;


    bool setWorldXform(const omni::fabric::PathC path, const usdrt::GfMatrix4d xform) noexcept;


    void trackWorldXformChanges(bool enabled) noexcept;


    void setTimeSampledXformHint(double newTime, bool resyncOccurred) noexcept;


    void markTimeSampledXformDirty(const omni::fabric::PathC path) noexcept;


    void trackLocalXformChanges(bool enabled) noexcept;


    bool getResetXformStack(const omni::fabric::PathC path) noexcept;


    bool setResetXformStack(const omni::fabric::PathC path, bool reset) noexcept;


    void trackResetXformStackChanges(bool enabled) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline omni::fabric::FabricId omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::getFabricId() noexcept
{
    return getFabricId_abi();
}

inline void omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::updateWorldXforms() noexcept
{
    updateWorldXforms_abi();
}

inline usdrt::GfMatrix4d omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::getLocalXform(
    const omni::fabric::PathC path) noexcept
{
    return getLocalXform_abi(path);
}

inline bool omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::setLocalXform(const omni::fabric::PathC path,
                                                                                         const usdrt::GfMatrix4d xform) noexcept
{
    return setLocalXform_abi(path, xform);
}

inline usdrt::GfMatrix4d omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::getWorldXform(
    const omni::fabric::PathC path) noexcept
{
    return getWorldXform_abi(path);
}

inline bool omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::setWorldXform(const omni::fabric::PathC path,
                                                                                         const usdrt::GfMatrix4d xform) noexcept
{
    return setWorldXform_abi(path, xform);
}

inline void omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::trackWorldXformChanges(bool enabled) noexcept
{
    trackWorldXformChanges_abi(enabled);
}

inline void omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::setTimeSampledXformHint(double newTime,
                                                                                                   bool resyncOccurred) noexcept
{
    setTimeSampledXformHint_abi(newTime, resyncOccurred);
}

inline void omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::markTimeSampledXformDirty(
    const omni::fabric::PathC path) noexcept
{
    markTimeSampledXformDirty_abi(path);
}

inline void omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::trackLocalXformChanges(bool enabled) noexcept
{
    trackLocalXformChanges_abi(enabled);
}

inline bool omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::getResetXformStack(
    const omni::fabric::PathC path) noexcept
{
    return getResetXformStack_abi(path);
}

inline bool omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::setResetXformStack(const omni::fabric::PathC path,
                                                                                              bool reset) noexcept
{
    return setResetXformStack_abi(path, reset);
}

inline void omni::core::Generated<usdrt::hierarchy::IFabricHierarchy_abi>::trackResetXformStackChanges(bool enabled) noexcept
{
    trackResetXformStackChanges_abi(enabled);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
