import functools
import os
import re
import time
import logging
import uuid

import omni.core
import carb.settings
import carb
import omni.ext
import omni.kit.app
import omni.structuredlog

logger = logging.getLogger(__name__)



# Link was generated by perflab Sentry instance:
DSN = None

CARB_LOG_LEVEL_TO_EVENT_LEVEL = {
    carb.logging.LEVEL_VERBOSE: "debug",
    carb.logging.LEVEL_INFO: "info",
    carb.logging.LEVEL_WARN: "warning",
    carb.logging.LEVEL_ERROR: "error",
    carb.logging.LEVEL_FATAL: "fatal",
}


class _Extension(omni.ext.IExt):

    def on_startup(self):
        app = omni.kit.app.get_app()

        settings = carb.settings.get_settings()
        has_started = start_sentry(app, settings)
        if has_started:
            self._configure_logger()


    def _configure_logger(self):
        """Subscribe to IApp log listener which outputs carbonite log errors each frame on the main thread

        We could have created custom python logger here, but it is known to create deadlocks with GIL because of being
        called from many threads.
        """
        sentry_sdk = _get_sentry_sdk()
        def on_log_event(e):
            level = e.payload["level"]
            if level >= carb.logging.LEVEL_ERROR:
                event = {}
                event["level"] = CARB_LOG_LEVEL_TO_EVENT_LEVEL.get(level, "notset")
                event["logger"] = e.payload["source"]
                event["logentry"] = {
                    "message": e.payload["message"],
                    "params": (),
                }
                event["extra"] = {
                    "filename": e.payload["filename"],
                    "functionName": e.payload["functionName"],
                    "lineNumber": e.payload["lineNumber"],
                }

                sentry_sdk.capture_event(event)

        log_stream = omni.kit.app.get_app().get_log_event_stream()
        self._log_sub = log_stream.create_subscription_to_pop(
            on_log_event, name="omni.kit.telemetry.sentry_extension"
        )


def should_enable_sentry(app, settings) -> bool:
    """Verifies if we're an external build or disabled via settings.

    Args:
        app (omni.App): The application
        settings (carb.settings): Carb dictionary
    """
    if app.is_app_external():
        logger.info("sentry is disabled for external build")
        return False

    if not settings.get("/telemetry/enableSentry"):
        return False

    return True


def filter_path_from_string(input_str: str, app_root_path: str | None = None) -> str:
    """If there's a path on the string we get rid of everything up to the root path."""
    all_lines = []
    for line in input_str.split("\n"):
        line = line.replace("\\", "/")
        if line.startswith("--"):
            words_in_line = line.split("=")
        else:
            words_in_line = line.split(" ")
        new_line = []
        for word in words_in_line:
            if not word.startswith("--") and word.count("/") > 1:
                if app_root_path and app_root_path in word:
                    # split on the root path, and only save everything after that.
                    word = word.split(app_root_path)[-1]
                else:
                    last_idx = word.rfind("/")
                    word = word[last_idx:]
            new_line.append(word)

        if line.startswith("--"):
            all_lines.append("=".join(new_line))
        else:
            all_lines.append(" ".join(new_line))

    return "\n".join(all_lines)

def remove_sentry_pii_data(event, hint, app_root_path: str | None = None) -> dict:
    """Tries our best to remove PII data from sentry events.

    We replace userId by the sessionId (unique integer per whole session) and replace any paths we find in the
        message or stack trace with their last part of the path, e.g: /home/foo/bar.py becomes bar.py

    Args:
        event (dict): The event that we filter
        hint (dict): Not used but part of the API
        app_root_path (str or None): the root path of the app. Everything before this is considered PII

    Returns:
        dict: The filtered event.
    """
    event.pop("server_name", "")
    filter_func = functools.partial(filter_path_from_string, app_root_path=app_root_path)
    if event.get("logentry", {}).get("message", ""):
        event['logentry']['message'] = filter_func(event['logentry']['message'])

    if event.get("logentry", {}).get("formatted", ""):
        event['logentry']['formatted'] = filter_func(event['logentry']['formatted'])

    if event.get("extra", {}).get("filename", ""):
        event['extra']['filename'] = filter_func(event['extra']['filename'])

    if event.get("extra", {}).get("sys.argv", []):
        new_argv = []
        for arg in event['extra']['sys.argv']:
            new_argv.append(filter_func(arg))
        event['extra']['sys.argv'] = new_argv

    if event.get("breadcrumbs", {}).get("values", []):
        for value in event['breadcrumbs']['values']:
            value['message'] = filter_func(value['message'])

    # Replace the user info with a UUID that is unique to a machine
    event["user"] = {"id": _get_machine_id()}

    return event


def _get_machine_id():
    """Return an identifier that is unique to the machine this is being run on, without any PII"""
    return uuid.uuid5(uuid.NAMESPACE_DNS, "nvidia.com").hex


def _get_sentry_sdk():
    import sentry_sdk
    return sentry_sdk

def _get_sentry_logging_integration():
    from sentry_sdk.integrations.logging import LoggingIntegration
    return LoggingIntegration

def start_sentry(app, settings) -> bool:
    """Starts sentry if it should.

    Returns:
        bool: Returns True if sentry started
    """
    if not should_enable_sentry(app, settings):
        if app.is_app_external():
            logger.info("sentry is disabled for external build")
        else:
            logger.debug("setting enableSentry disabled")
        return False

    global DSN
    DSN = settings.get("/telemetry/dsn")
    remove_pii = settings.get("/telemetry/removePIISentry")
    app_root_path = settings.get("/telemetry/appRootPath")

    # Imports are deferred for start up time and on a function for easier to mock
    sentry_sdk = _get_sentry_sdk()
    logging_integration = _get_sentry_logging_integration()

    # Setup user using already formed crashreporter data
    data = settings.get("/crashreporter/data")
    if not data:
        data = {}

    user_id = data.get("userId", None)
    if user_id:
        sentry_sdk.set_user({"id": user_id})

    time_start = time.monotonic()

    sentry_sdk.set_tag("app.name", app.get_app_name())
    sentry_sdk.set_tag("app.version", app.get_app_version())
    sentry_sdk.set_tag("app.environment", app.get_app_environment())
    sentry_sdk.set_tag("app.kit_version", app.get_kit_version())

    # Pass telemetry session to sentry
    structlog_settings = omni.structuredlog.IStructuredLogSettings()
    if structlog_settings:
        sentry_sdk.set_tag("session_id", str(structlog_settings.session_id))

    sentry_options = {
        "dsn": DSN,
        "auto_enabling_integrations": False,
        "integrations": [logging_integration(event_level=None, level=None)],
        "release": f"{app.get_app_name()}-{app.get_app_version()}"
    }
    if remove_pii:
        remove_func = functools.partial(remove_sentry_pii_data, app_root_path=app_root_path)
        sentry_options["before_send"] = remove_func

    sentry_sdk.init(**sentry_options)
    logger.info(
        "enabled Sentry...(time took: {:.2f}s)".format(time.monotonic() - time_start)
    )
    return True
