[package]
# Semantic Versioning is used: https://semver.org/
version = "0.2.0"

category = "Internal"
support_level = "Core"

authors = ["NVIDIA"]

title = "Loop Runner"
description = "Default implementation of omni::kit::IRunLoopRunner, an interface that pumps global update events"

repository = ""

keywords = ["kit", "loop"]

# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"

[[native.plugin]]
path = "bin/*.plugin"
recursive = false


[settings]
# Don't sync threads to the present thread
app.runLoopsGlobal.syncToPresent = false

# Frequency limit can be enabled per run loop:
app.runLoops.main.rateLimitEnabled = true
app.runLoops.main.rateLimitFrequency = 120
app.runLoops.main.rateLimitUseBusyLoop = false
app.runLoops.main.update.enabled = true

app.runLoops.present.rateLimitEnabled = true
app.runLoops.present.rateLimitFrequency = 120
app.runLoops.present.rateLimitUseBusyLoop = false
app.runLoops.present.update.enabled = true

app.runLoops.rendering_0.rateLimitEnabled = true
app.runLoops.rendering_0.rateLimitFrequency = 120
app.runLoops.rendering_0.rateLimitUseBusyLoop = false
app.runLoops.rendering_0.update.enabled = true


[[test]]
waiver = "Tests are in omni.kit.core.tests"

[documentation]
python_api_hidden = true
cpp_api_hidden = true
pages = [
    "docs/Overview.md",
    "docs/SETTINGS.md",
    "docs/CHANGELOG.md",
]
